services:
  todo-db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: topsecret
    ports:
      - 5432:5432
    volumes:
      - todo-app:/var/lib/postgresql/data
  todo-client:
    image: client
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend/
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules 
      - type: bind
        source: ./frontend/vite.config.js
        target: /usr/src/app/vite.config.js
    ports:
      - 5173:5173
  todo-nginx:
    image: todo-nginx
    build:
      context: ./frontend/
      dockerfile: Dockerfile.prod
    ports:
      - 8085:80
  todo-api:
    image: todo-api
    depends_on: 
      - todo-db
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    ports: 
      - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://todo-db:5432/postgres
      SPRING_DATASOURCE_PASSWORD: topsecret
      SPRING_DATASOURCE_USER: postgres
      API_VERSION: dev
volumes:
  todo-app:
