services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - todo-app:/var/lib/postgresql/data
  client:
    image: client
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend/
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules 
      - type: bind
        source: ./frontend/vite.config.js
        target: /usr/src/app/vite.config.js
    ports:
      - 5173:5173
  api:
    # names the service.
    image: spring-api
    # Where the source code and Dockerfile live.
    depends_on: 
      - db
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    ports: 
      - 8081:8080
    # Set this so spring can find the db as it differs from on localhost.
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
volumes:
  todo-app:
